apiVersion: v1
kind: Service
metadata:
  name: guestbook-frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  selector:
    app: guestbook
    tier: frontend
  ports:
  - port: 9080
    targetPort: http-server
